# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-US
title: SPARKLERS:We Are The Makers
email: arijit1080@gmail.com
description: "Official Blog Of Sparklers"
baseurl: "/blog"  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Arijit Das
  twitter: arijit1080
  picture: /blog/assets/images/logo.jpg
facebook_username: sparklers2018
github_username: Sparklers-The-Makers
logo: /assets/icons/logo.jpg
google_analytics: UA-136947764-1
disqus:
  shortname: sparklers
search: true
search_full_content: true
search_provider: lunr
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: # true (default), false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Asia/Calcutta # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
people:
- name: Arijit Das
  pic: 3
  position: Computer Science Engineering Student
  social:
    - title: linkedin
      url: www.linkedin.com/in/arijit-das-1080
    - title: facebook
      url: https://www.facebook.com/people/Arijit-Das/100009569555607
    - title: envelope
      url: mailto:arijit1080@gmail.com
- name: Ayan Dey
  pic: 1
  position: Phd Research Scholar
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/ayan.dey.528
    - title: envelope
      url: mailto:deyayan9@gmail.com

- name: Rahul Dutta
  pic: 2
  position: Computer Science Engineering Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/stack.overflowww
    - title: envelope
      url: mailto:farazfarhat2@gmail.com



# Plugins
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Jekyll Feed
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
---
layout: default
comments: true
# other options
---
